# Exported from Render on 2024-07-05T08:08:49Z
databases:
- name: doan
  databaseName: doan_8vmx
  user: minhthuan
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: doan
  runtime: ruby
  repo: https://github.com/thuannghi1/doan
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: oregon
  buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
  startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
version: "1"
